### ISSUE TITLE
Paws::Support::DescribeTrustedAdvisorCheckResult fails constraint validation

### ISSUE THREAD

**Issue by rpcme** [pplu/aws-sdk-perl#107]
Supposed to return a `DescribeTrustedAdvisorCheckResultResponse`.

Call:

``` perl
my $client = Paws->service('Support', region => 'us-east-1');
my $results = $client->DescribeTrustedAdvisorCheckResult(CheckId => $rule_id);
```

Result (abbreviated):

``` bash
Attribute (Metadata) does not pass the type constraint because: Validation failed for 'ArrayRef[Str]' with value ARRAY(0x7fa42b8ded90)
<snip>
```

I will be looking at a fix after posting this.

**Comment by rpcme** [comment]
Well, the culprit I think is that some values for metadata can be null, i.e.:

```json
"flaggedResources":[
                { "isSuppressed":false,
                  "metadata":["us-west-1c","i-XXXXXXXXX",null,"t2.micro","$12.24","0.1%  0.00MB","0.1%  0.00MB","0.1%  0.00MB","0.1%  0.00MB","0.1%  0.00MB","0.1%  0.00MB","0.1%  0.00MB","0.1%  0.00MB","0.1%  0.00MB","0.1%  0.00MB","0.1%  0.00MB","0.1%  0.00MB","0.1%  0.00MB","0.1%  0.00MB","0.1%","0.00MB","14 days"],
                  "region":"us-west-1",
                  "resourceId":"g5n5HNAeFnNFMWfJAPleOQLFFjqrd_CNDztQLmwG1Qo","status":"warning"},
```

**Comment by rpcme** [comment]
More information.

The boto sdk has this named:
```json
        "metadata":{
          "shape":"StringList",
          "documentation":"<p>The column headings for the data returned by the Trusted Advisor check. The order of the headings corresponds to the order of the data in the <b>Metadata</b> element of the <a>TrustedAdvisorResourceDetail</a> for the check. <b>Metadata</b> contains all the data that is shown in the Excel download, even in those cases where the UI shows just summary data. </p>"
        }
```

I checked resulting values given by python and `None` is an allowable value for `StringList`.  Shouldn't Paws mirror this behavior by allowing `undef` as well?

**Comment by rpcme** [comment]
I got on #moose and mst let me know we should be able to do:

```perl
isa => ArrayRef[Str|Undef]
```
@pplu I think we need to discuss if this is a global thing or an override before doing any hacking on it.

In other news, mst mentioned Type::Library and Type::Standard should be used in lieu of MooseX::ClassAttribute.  Perhaps something to do future wise.

**Comment by pplu** [comment]
OK, so I see three things here:

1- Using Type::Library and Type::Standard in Paws instead of "Moose types": I'm OK with that for the future if it's the recommended way. I'll open a ticket to track that (#109)

2- MooseX::ClassAttribute: It's used to have data attached to a class (and not to an instance). I'm not sure how Type::Library and Type::Standard can help to substitute MooseX::ClassAttribute (we can continue this conversation in another ticket so this one stays monotematic)

3- Converting "ArrayRef[Str]" to "ArrayRef[Str|Undef]"

>I think we need to discuss if this is a global thing

I think it's not a global thing (maybe it's just TrustedAdvisor that has this behaviour). I'm not aware of any flag in the botocore definition files that signals "there can be nulls in this array", so we can't decide how we can select one type or the other :(

From my personal experience: It looks like botocore and the other SDKs are very lax with the way they process the responses from the APIs. 

 - Things like "enums" in response objects seem to not be validated/filtered (it's not unsusual to see incorrect values in the json definition files for enums). Very early on, Paws had to abandon using Moose Enums as attribute constraints because of that fact.

- Some response shapes are incorrect in the json definition files

Those are the reasons why I maintain a botocore fork (just to adapt the strictly necessary things to keep Paws correct).

So I see a some things we can do (they are not necessarily mutually exclusive)

- Just convert all ArrayRef[Str] to ArrayRef[Str|Undef]. After all: it doesn't break anything. Not very elegant, but at least it gets things working.

- Change the type for StringList to StringListWithNulls, create a shape StringListWithNulls with some type of flag that signals that the array can contain nulls. Try to get that proposal in to the AWS definition files, and them to signal "there can be nulls in this array" for other services.

**Comment by rpcme** [comment]
Hello, I received feedback on this issue.

In Python, str() is a nullable type.   Meaning, str(None) results in 'None'.  From an API perspective, the result is legal.

So, I think it is fully OK to do ArrayRef[Str|Undef].

**Comment by pplu** [comment]
Hi!

   In https://github.com/pplu/aws-sdk-perl/tree/str_or_undef_arrays you have the Str|Undef applied to all objects. If you're confortable with the change, I'll merge it to master. In the long term I'd love to get some type of information on the nullability of elements in an array so only the nullable arrays can be as nullable.

**Comment by rpcme** [comment]
I am comfortable with the change.

Right now we are working against a reference implementation rather than a specification.  I haven't done it yet but it would be interesting to see the result via the Java SDK to understand if this is a reflection of the reference implementation language or the REST API's intent.  If the result is dissimilar between Java and Python then it very well could be a reflection of the former; if similar, then I think there is a good case for making nullability more explicit.

**Comment by pplu** [comment]
Hi,

  Note that this change was pushed to CPAN on Paws 0.29 (a week ago)
