### ISSUE TITLE
Add requestId as a return value on EC2::CreateImage

### ISSUE THREAD

**Issue by as0ler** [pplu/aws-sdk-perl#17]
When you create an image, the result should return the "requestId".

I guess It should be added on the CreateImageResult class.

**Comment by as0ler** [comment]
The use case is to continuously request the state of the image Created, to have a timer on the external application. That's the reason a Request Id could be needed.

As you see, it's no so important.

**Comment by pplu** [comment]
Hi,
  If you're using CreateImage, aren't you looking to recieve the ImageId (which Paws does return), and then poll DescribeImages until your image is complete?

**Comment by glenveegee** [comment]
This ought to do it for all requests. In Paws::API::Caller::response_to_object add the following just before returning the object:

<pre>
$o_result->{requestId} = $unserialized_struct->{'requestId'} 
                        || $unserialized_struct->{'RequestId'} 
                        || $headers->{'x-amz-request-id'} 
                        || $headers->{'x-amzn-requestid'};
</pre>

**Comment by pplu** [comment]
We always (or try to) return the requestid if there is an exception.

I've always been doubting how to expose the requestid for successful calls. Would you go for an attribute called "RequestId" (or some name unused by AWS) on all response objects? Or do you have another idea?

**Comment by glenveegee** [comment]
RequestId is an attribute of all calls made to the AWS REST API and so I think (regardless of how useful it may be) it should always be returned whether it's an error or not. What I proposed above is a catch all solution for successful calls to the API and would add an undocumented attribute to all response objects. I've also tried fixing the templates for the API builder. It's more a case or laziness because there are 5 different builders (restxml, EC2, restjson...) and hence template snippets to keep track of. 

The picture is further complicated by AWS inconsistencies - for example:

The EC2 documentation for DescribeInstances clearly indicates a requestId field for the response

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html#API_DescribeInstances_ResponseElements

but the boto definition has no such field and this is why EC2 calls don't return requestId.


Perhaps a compromise would be to obfuscate the request id so that all response objects (excluding exceptions) git a pseudo private `_request_id` attribute as above. This would be no worse that the current situation and we could guarantee that we don't clash with "legitimate" RequestId attributes in the responses as defined in the boto shema

**Comment by pplu** [comment]
a `_request_id` attribute looks good. If you do it for rest-xml APIs (which I know you're working on), I'll complete for the rest of APIs ;)

**Comment by pplu** [comment]
@glenveegee. I've started a branch with your suggestion: https://github.com/pplu/aws-sdk-perl/tree/request_id. All service responses now have a _request_id attribute, and Paws::API::Caller sets it.

I've added one more case (RequestId value inside a RequestMetadata tag), and added tests for all cases we already have recorded that can verify the correct functionality :smile:

There is a corner case I'm not sure how to cover: Methods that don't return an object: If they succeed, Paws is returning a 1. There isn't an object to return the request id attached to. Any ideas?

**Comment by glenveegee** [comment]
Do you have an example of a method that results in 1 being returned. I've not given it mush thought and I still have to look at the code but if we returned  `{_request_id => 'THEREQUESTID'}` then we wouldn't break anything because the return value would still evaluate as truthy.

**Comment by pplu** [comment]
To have a list of methods that don't return objects:

```
ack-grep "class_has _returns .* is => 'ro'\)" auto-lib/
```

**Comment by glenveegee** [comment]
Check out my latest PR (https://github.com/pplu/aws-sdk-perl/pull/119)

**Comment by pplu** [comment]
This issue was solved some time ago
