### ISSUE TITLE
SNS - CheckIfPhoneNumberIsOptedOut is not working correctly

### ISSUE THREAD

**Issue by SeptamusNonovant** [pplu/aws-sdk-perl#312]
Hello,

When using the SNS method `CheckIfPhoneNumberIsOptedOut(PhoneNumber => $phone_number)`, the `isOptedOut` parameter is not being returned.  All I am getting back is a `_requestId`:

```
$VAR1 = bless( {
                 '_request_id' => 'f6e9766d-8e0a-5f31-9d46-22f298eb8ada'
               }, 'Paws::SNS::CheckIfPhoneNumberIsOptedOutResponse' );
```

I'm not sure if the issue is the casing of some of the parameters, but here is how AWS takes it:
`http://sns.us-east-1.amazonaws.com/?Action=CheckIfPhoneNumberIsOptedOut&Version=2010-03-31&phoneNumber=15555554444`

And here is the XML response:
```
<CheckIfPhoneNumberIsOptedOutResponse
	xmlns="http://sns.amazonaws.com/doc/2010-03-31/">
	<CheckIfPhoneNumberIsOptedOutResult>
		<isOptedOut>false</isOptedOut>
	</CheckIfPhoneNumberIsOptedOutResult>
	<ResponseMetadata>
		<RequestId>aad6a426-1470-541b-af1d-f0b9035a2eac</RequestId>
	</ResponseMetadata>
</CheckIfPhoneNumberIsOptedOutResponse>
```

Note the "p" in `phoneNumber` is lowercase, as is the "i" in `isOptedOut`

Thanks.

**Comment by pplu** [comment]
Hi @SeptamusNonovant,

   Thanks for reporting this issue in a way it has helped trace down the problem immediately. I've opened a branch https://github.com/pplu/aws-sdk-perl/tree/fix/issue_312 for fixing it.

   It's due to an error in the way the SNS classes are being generated (the fact that the attribute is returned in an xml key that is differently named is being ignored by the code generators). Luckily Paws already has infrastructure to support this case, so a quick fix is feasable. I've created a test case, and a quick fix that you can apply for the method you report: https://github.com/pplu/aws-sdk-perl/commit/add18c481aa9b2e717498d2ad315b3c871aab4b9

   Please report if more methods you're using are affected by this bug (I suspect that some "new" methods are affected).

**Comment by pplu** [comment]
In https://github.com/pplu/aws-sdk-perl/pull/313/commits/c5a775a739f99ca812cf7df7bd69d1e2cd76f95b you have a couple more classes that are affected.

**Comment by SeptamusNonovant** [comment]
Hello,

Thanks for taking care of this so quickly. The fix looks good.

Thanks!
