### ISSUE TITLE
SQS DeleteMessageBatch Request failing

### ISSUE THREAD

**Issue by mbartold** [pplu/aws-sdk-perl#36]
The error I get is "Top level element may not be treated as a list"

I dug into the code and dumped what was being sent, and saw that "Entries.1.Id=" is being sent. From the documentation https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_DeleteMessageBatch.html it looks like it should be "DeleteMessageBatchRequestEntry.1.Id=".

Changing the key (s/Entries/DeleteMessageBatchRequestEntryList/) in the SQS/DeleteMessageBatch.pm fixes the issue. Internal documentation should also be updated in SQS.pm, and SQS/DeleteMessageBatch.pm

**Comment by pplu** [comment]
Thanks for the report! It looks like the botocore files for SQS don't have a "location" attribute that tells us to put the "Entries" attribute in "DeleteMessageBatchRequestEntry".

The intention, though, would be to have Entries in the call, and not DeleteMessageBatchRequestEntryList. Can you try to, instead of s/Entries/DeleteMessageBatchRequestEntryList/, put
```
has Entries => ( ..., traits => ['NameInRequest'], request_name => 'DeleteMessageBatchRequestEntryList');
 ```
into the Entries attribute declaration?

Does it work? (note: I think you will find more places in SQS that require this pattern to be applied (anywhere there is an Entries attribute)

**Comment by mbartold** [comment]
Yes, that works.

Thanks!

**Comment by pplu** [comment]
Great! That way, when I update the SDK to fix the bug, it will keep working for you. 

If you are going to use ChangeMessageVisibilityBatch and/or DeleteMessageBatch, the same thing is prone to happen. If you fix them, please send in the changes ;)

I'll leave this bug open until a release to CPAN that fixes it is available

Cheers,
pplu

**Comment by pplu** [comment]
Yesterday I pushed 0.12 to CPAN with a fix for Batch operations. Feel free to upgrade :)
