### ISSUE TITLE
Can't send raw mail via SESv2

### ISSUE THREAD

**Issue by Jamerswu** [pplu/aws-sdk-perl#397]
Test code:

```
#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';
use Paws;
use Data::Dumper;

my $email = Paws->service('SESv2', region => 'us-east-1');

my $res = $email->SendEmail(
    Content          => {
        Raw    => {
            Data => 'From: noreply@xxx\nTo: xxx@xxx.xxx\nSubject: Test email \nMIME-Version: 1.0\nContent-type: Multipart/Mixed; boundary="NextPart"\n\n--NextPart\nContent-Type: text/plain\n\nThis is the message body.\n\n--NextPart'
        },
    },
    FromEmailAddress => 'noreply@xxxxx',
    Destination      => {
        ToAddresses => ['xxx@xxx.xxx',],
    },
);
print Dumper($res);

```

The code is executed successfully, but the received email contains garbled characters, and everything is normal when sending emails in Simple mode. Did I do something wrong?
<pre>
锟�&锟斤拷锟斤拷e锟斤拷.锟斤拷锟斤拷堍o锟絅锟斤拷锟斤拷锟斤拷锟斤拷锟斤拷锟斤拷?r锟斤拷锟�+锟斤拷锟�-锟斤拷薏锟睫欙拷锟斤拷锟斤拷 锟�?U锟届妷锟斤拷_锟斤拷p锟斤拷拽锟斤拷r锟斤拷锟�2锟絤锟斤拷锟斤拷锟�"锟斤拷锟斤拷.锟街拷锟斤拷{Oj锟�锟�锟斤拷锟絕锟斤拷诋锟斤拷
锟斤拷z{O*^锟斤拷^锟斤拷闀拷锟�锟絅锟斤拷+?锟�锟斤拷锟�,j锟絥锟絩锟斤拷锟斤拷锟斤拷{Oj锟絆
From: noreply@xxxx
Message-ID: <xxxxx@email.amazonses.com>
Date: Fri, 15 Jan 2021 03:37:26 +0000
X-SES-Outgoing: 2021.01.15-54.240.11.100
Feedback-ID: 1.us-east-1.xxx:AmazonSES
</pre>

**Comment by pplu** [comment]
Hi,

   What simple mode are you referring to? do you have a code example of "simple mode¨ that sends the same email successfully?

**Comment by Jamerswu** [comment]
@pplu Thanks for your reply. Following is the simple mode code example.

```
#!/usr/bin/perl
use strict;
use warnings FATAL => 'all';
use Paws;
use Data::Dumper;

my $email = Paws->service('SESv2', region => 'us-east-1');

my $res = $email->SendEmail(
    Content          => {
        Simple => {
            Body    => {
                Text => {
                    Data    => 'Hello world!',
                    Charset => 'UTF-8',
                }
            },
            Subject => {
                Data    => 'Test SESv2 mail',
                Charset => 'UTF-8',
            }
        }
    },
    Destination      => {
        ToAddresses => ['xxx@xxx.xxx',],
    },
    FromEmailAddress => 'noreply@xxxxx',
);
print Dumper($res);
```

**Comment by pplu** [comment]
I *think* that the problem is not coming from the way the SDK is forming the API call to SES.

To know exactly what the SDK is sending to the API, in https://github.com/pplu/aws-sdk-perl/blob/master/lib/Paws/Net/Caller.pm#L19, you can `use Data::Dumper: print Dumper($requestObj)`. This should at least help you confirm that the SDK is not doing any strange stuff.

Sometimes forming MIME messages is more subtle and delicate than expected (I've had experience with different mail clients rendering the same MIME in radically different ways). Have you tried sending the MIME content from a library that outputs "valid" MIME? (MIME::Lite, for example).

Also take into account that SESv2 seems to be manipulating the message, even using SendRawEmail: https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html:

> Amazon SES allows you to specify 8-bit Content-Transfer-Encoding for MIME message parts. However, if Amazon SES has to modify the contents of your message (for example, if you use open and click tracking), 8-bit content isn't preserved. For this reason, we highly recommend that you encode all content that isn't 7-bit ASCII. For more information, see MIME Encoding in the Amazon SES Developer Guide.

Note that your MIME in the SendRawEmail example doesn't specify the content encoding, so maybe SES is garbling the message in some strange way due to a false assumption of the encoding of the message.

Hope it helps!

**Comment by pplu** [comment]
Hi,

   Did you get it to work? Can you make 2cts of what was going on?

**Comment by Jamerswu** [comment]
@pplu I didn't solve this problem, and then I used SMTP to send mail through SES.

I will try it if I have time. Thank you all.
