### ISSUE TITLE
How to switch endpoints (f.ex. in ML)

### ISSUE THREAD

**Issue by dtikhonov** [pplu/aws-sdk-perl#47]
For real-time Machine Learning predictions [1], one has to specify a different endpoint [2].  This property is returned by GetMLModel call [3].  Looking at the Paws code, it is not clear to me how to switch endpoints mid-stream.  I was able to force it as follows:

``` perl
# Get model information:
my $model = $ml->GetMLModel(MLModelId => $model_id);
my $endpoint_url = $model->EndpointInfo->EndpointUrl;

# Beat underlying object(s) into submission:
my $ei = $ml->_endpoint_info;
$ei->{uri} =~ s/({service})/realtime.$1/;
my $template = URI::Template->new($endpoint_url);
my $url = $template->process();
$ei->{url} = $url;
$ml->{endpoint_host} = $url->host;
$ml->{_api_endpoint} = $endpoint_url;

# Now we can Predict:
my $predict = $ml->Predict(...);
```
1. http://docs.aws.amazon.com/machine-learning/latest/APIReference/API_Predict.html#amazonml-Predict-request-PredictEndpoint
2. Currently, they just tack on "realtime." in front of the hostname.
3. http://docs.aws.amazon.com/machine-learning/latest/APIReference/API_RealtimeEndpointInfo.html

**Comment by pplu** [comment]
Wow! That's a surprise (Some services are special in their own way :smile:). Since ML is quite new, these types of behaviours haven't been detected yet: you're the first to pop up with reports and doubts (thanks for the patience, the reporting and bashing the code into submission. It helps!).

I'm thinking that what you can do is invoke $paws->service('ML'...) specifying an endpoint, getting a new object to call the API, instead of changing the object mid-stream (breaking the possibility for re-calling $model->EndpointInfo, for example)

So the flow would go something like:
```
my $paws = Paws->new;
my $ml = $paws->service('ML');
my $model = $ml->GetMLModel(MLModelId => $model_id);
my $endpoint_url = $model->EndpointInfo->EndpointUrl;

my $predictor = $paws->service('ML', _endpoint_info => { url => URI->new($endpoint_url) });
$predictor->Predict(...);
```
I never thought that the _endpoint_info attribute would be needed as a public accessor. If this works for you, we'll find a way to officially make the "change my endpoint" API publically available in a decent manner :laughing: (note: the behaviour we're changing is all in Paws::API::EndpointResolver)

Cheers,

Jose Luis

**Comment by dtikhonov** [comment]
What you suggest does not work (I tried something similar before) -- the request is still sent to 'https://machinelearning.us-east-1.amazonaws.com/'.  I _think_ that the endpoint resolver calls `service()`, whose return value is hardcoded, and maps that to an endpoint, losing the new URI in the process.  There are a lot of things going on when a call is made, I haven't understood it fully yet.

**Comment by pplu** [comment]
OK, lets try another way:
```
my $predictor->service('ML', region_rules => [ { uri => $endpoint_url } ]);
```

**Comment by dtikhonov** [comment]
This works -- thank you.

**Comment by pplu** [comment]
Just pushed 0.33 to CPAN with an update on this issue:

now when instance a service, you should be able to specify an endpoint. The region is required to sign the request.
```
my $predictor = $paws->service('ML', endpoint => $endpoint_url, region => 'xxx');
$predictor->Predict(...);
```
