### ISSUE TITLE
potential speed gain by immutabilizing Moose classes

### ISSUE THREAD

**Issue by karenetheridge** [pplu/aws-sdk-perl#54]
I noticed you're using Moose heavily, but the classes are not doing `__PACKAGE__->meta->make_immutable` anywhere. Adding that will impose a small startup penalty, but will greatly speed up runtime operations.

**Comment by karenetheridge** [comment]
see https://metacpan.org/pod/distribution/Moose/lib/Moose/Manual/BestPractices.pod#namespace::autoclean-and-immutabilize

**Comment by pplu** [comment]
Hi!

Thanks for the suggestion!The non-inclusion of make_immutable is on purpouse, though. The thought is to not penalize startup time for short-lived programs (cli usage). The intention is to call $class->meta->make_immutable when loading the different classes at runtime if the SDK is configured to do so (if the user specifies that he wants runtime optimization at the cost of runtime).

I haven't implemented this behaviour yet, because I would want to benchmark first and confirm if it will really make a difference to allow the make_immutable to be turned off for CLI usage. Maybe you can help me on that with your experience. Do you think there will be a real impact to CLI usage if I put the make_immutable in all classes? Should I bother to make the "make_immutable" optional?

**Comment by karenetheridge** [comment]
I'd either just add `make_immutable` everywhere (e.g. Dist::Zilla is a command-line application and has *lots* of component classes, and it does it everywhere with little apparent loss), or convert to Moo, which doesn't impose such a penalty.

**Comment by pplu** [comment]
Hi,

I've benchmarked a bit, and there is a noticeable performance penalty for CLI usage, so I've made immutability optional. Right now in master you have an example of how to make it work: examples/mutability.pl, and the code I've used to benchmark.

Any comments would be appreciated before making this go live to CPAN (ETA a week or so)

**Comment by pplu** [comment]
Hi,

Version 0.17 has just hit CPAN with this issue solved (you can activate immutabilization like in examples/mutability.pl)
