### ISSUE TITLE
Random test failures

### ISSUE THREAD

**Issue by eserte** [pplu/aws-sdk-perl#76]
See http://matrix.cpantesters.org/?dist=Paws%200.19 for an overview. According to http://analysis.cpantesters.org/solved?distv=Paws-0.19 the t/15_timeouts.t and t/01_load.t tests fail more often than the others.

**Comment by pplu** [comment]
Hi!

   Thanks for the info! 

   It looks like 01_load is picking up Paws::RegionInfo from an old version of Paws (I suppose it's installed on the testers system, and since the test loads anything in the Paws:: namespace). I've fixed it in f904d46c62219af982d3f87c69db5db07cfaec4a

  15_timeout is probably failing due to load and scheduling issues on the smokers machines (same happened on travis). I'll skip the test for anyone not an author (so installations can succeed): fa12701a7700b909b631c3b6931acf20e79e8c3a

**Comment by pplu** [comment]
I've pushed 0.20 to CPAN with these changes. I hope it fixes the issues
