### ISSUE TITLE
[Kinesis] Error: Unrecognized error message format

### ISSUE THREAD

**Issue by ribugent** [pplu/aws-sdk-perl#82]
Sometimes running a GetRecords on Kinesis I got this error

`Unrecognized error message format /opt/plenv/versions/5.14.2/lib/perl5/site_perl/5.14.2/Paws/Net/JsonResponse.pm line 26.
`

I did a little debugging, the api returns a 500 http code and the following json:
`
{"__type":"InternalFailure"}
`

**Comment by pplu** [comment]
Hi!

Thanks for the concise report. It looks like Kinesis doesn't return the "message" field when it returns the InternalFailure error, and Paws doesn't like it. I've patched and tested in 40f1bf7fba6fd832873a30ced5c540e09953de52. I'm just making a special case for the InternalFailure, since it looks like the only case that doesn't return the message field. If you find any documentation or exeptions without the "message" field, please let me know.

Thanks,

Jose Luis

**Comment by pplu** [comment]
Hi,

A fix for this was pushed to CPAN in 0.22
